server:
  port: 8081
spring:
  application:
    name: '@project.artifactId@'
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://keycloak.issuer-uri
  webflux:
    problemdetails:
      enabled: true